import type { Metadata } from "next";
import "./globals.css";
import LayoutClient from "./layout.c.";
import GlowCursor from "@/animated/GlowCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <LayoutClient>
          <GlowCursor />
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
